# Generated by Django 4.0.4 on 2022-05-18 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_bot', '0002_alter_anime_description_alter_anime_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
